Homework5: Alina Shautsova
AlinaShautsova/pymar2024 pull request #4
Opened 2024-05-14 13:39 UTC by AlinaShautsova

2024-05-14 14:14 UTC, Stml89 requested changes

2024-05-14 14:14 UTC, Stml89 commented on homework5.py
> +print(S[1:-1])
s.strip() - is better to use here

2024-05-14 16:39 UTC, AlinaShautsova commented on homework5.py
> +print(S[1:-1])
Fixed

2024-05-29 19:57 UTC, Stml89 approved these changes
You can merge it now

2024-06-11 20:27 UTC, merged