Homework10: Alina Shautsova
AlinaShautsova/pymar2024 pull request #9
Opened 2024-06-08 19:06 UTC by AlinaShautsova

2024-06-11 19:51 UTC, Stml89 requested changes
Please, merge ALL approved PRs

2024-06-16 09:23 UTC, Stml89 requested changes

2024-06-16 09:23 UTC, Stml89 commented on homework10_return_number.py
> +        return result
```suggestion
        return result
```

2024-06-16 09:23 UTC, Stml89 commented on homework10_type_decorator.py
> +                new_args.append(type1(arg))
JFYI: Function `map` can also help here

2024-06-16 19:07 UTC, AlinaShautsova commented on homework10_return_number.py
> +        return result
Done

2024-06-16 19:31 UTC, AlinaShautsova commented on homework10_type_decorator.py
> +                new_args.append(type1(arg))
Done

2024-06-22 19:54 UTC, merged

2024-07-15 20:42 UTC, Stml89 reviewed
approved